/*
 * DIO_CFG.h
 *
 *  Created on: Apr 4, 2023
 *      Author: hodam
 */

#ifndef MCAL_DIO_CFG_H_
#define MCAL_DIO_CFG_H_

#define DIO_CNG_OUTPUT 		1
#define DIO_CNG_INPUT  		0

#define DIO_CNG_HIGH 		1
#define DIO_CNG_LOW  		0

#define DIO_CNG_PULLUP 		1
#define DIO_CNG_FLOATING  	0


#define PORTA_PIN0_DIRECTION  DIO_CNG_OUTPUT
#define PORTA_PIN1_DIRECTION  DIO_CNG_OUTPUT
#define PORTA_PIN2_DIRECTION  DIO_CNG_OUTPUT
#define PORTA_PIN3_DIRECTION  DIO_CNG_INPUT
#define PORTA_PIN4_DIRECTION  DIO_CNG_INPUT
#define PORTA_PIN5_DIRECTION  DIO_CNG_INPUT
#define PORTA_PIN6_DIRECTION  DIO_CNG_OUTPUT
#define PORTA_PIN7_DIRECTION  DIO_CNG_OUTPUT

#define PORTB_PIN0_DIRECTION  DIO_CNG_INPUT
#define PORTB_PIN1_DIRECTION  DIO_CNG_INPUT
#define PORTB_PIN2_DIRECTION  DIO_CNG_INPUT
#define PORTB_PIN3_DIRECTION  DIO_CNG_INPUT
#define PORTB_PIN4_DIRECTION  DIO_CNG_INPUT
#define PORTB_PIN5_DIRECTION  DIO_CNG_INPUT
#define PORTB_PIN6_DIRECTION  DIO_CNG_INPUT
#define PORTB_PIN7_DIRECTION  DIO_CNG_INPUT

#define PORTC_PIN0_DIRECTION  DIO_CNG_INPUT
#define PORTC_PIN1_DIRECTION  DIO_CNG_INPUT
#define PORTC_PIN2_DIRECTION  DIO_CNG_INPUT
#define PORTC_PIN3_DIRECTION  DIO_CNG_INPUT
#define PORTC_PIN4_DIRECTION  DIO_CNG_INPUT
#define PORTC_PIN5_DIRECTION  DIO_CNG_INPUT
#define PORTC_PIN6_DIRECTION  DIO_CNG_INPUT
#define PORTC_PIN7_DIRECTION  DIO_CNG_INPUT

#define PORTD_PIN0_DIRECTION  DIO_CNG_INPUT
#define PORTD_PIN1_DIRECTION  DIO_CNG_INPUT
#define PORTD_PIN2_DIRECTION  DIO_CNG_INPUT
#define PORTD_PIN3_DIRECTION  DIO_CNG_INPUT
#define PORTD_PIN4_DIRECTION  DIO_CNG_INPUT
#define PORTD_PIN5_DIRECTION  DIO_CNG_INPUT
#define PORTD_PIN6_DIRECTION  DIO_CNG_INPUT
#define PORTD_PIN7_DIRECTION  DIO_CNG_INPUT


/* Direction OUTPUT :- DIO_HIGH   - DIO_LOW */
/* Direction INPUT  :- DIO_PULLUP - DIO_FLOATING */

#define PORTA_PIN0_VALUE  DIO_CNG_HIGH
#define PORTA_PIN1_VALUE  DIO_CNG_HIGH
#define PORTA_PIN2_VALUE  DIO_CNG_HIGH
#define PORTA_PIN3_VALUE  DIO_CNG_HIGH
#define PORTA_PIN4_VALUE  DIO_CNG_HIGH
#define PORTA_PIN5_VALUE  DIO_CNG_HIGH
#define PORTA_PIN6_VALUE  DIO_CNG_HIGH
#define PORTA_PIN7_VALUE  DIO_CNG_HIGH

#define PORTB_PIN3_VALUE  DIO_CNG_FLOATING
#define PORTB_PIN3_VALUE  DIO_CNG_FLOATING
#define PORTB_PIN0_VALUE  DIO_CNG_FLOATING
#define PORTB_PIN1_VALUE  DIO_CNG_FLOATING
#define PORTB_PIN2_VALUE  DIO_CNG_FLOATING
#define PORTB_PIN4_VALUE  DIO_CNG_FLOATING
#define PORTB_PIN5_VALUE  DIO_CNG_FLOATING
#define PORTB_PIN6_VALUE  DIO_CNG_FLOATING
#define PORTB_PIN7_VALUE  DIO_CNG_FLOATING

#define PORTC_PIN0_VALUE  DIO_CNG_FLOATING
#define PORTC_PIN1_VALUE  DIO_CNG_FLOATING
#define PORTC_PIN2_VALUE  DIO_CNG_FLOATING
#define PORTC_PIN3_VALUE  DIO_CNG_FLOATING
#define PORTC_PIN4_VALUE  DIO_CNG_FLOATING
#define PORTC_PIN5_VALUE  DIO_CNG_FLOATING
#define PORTC_PIN6_VALUE  DIO_CNG_FLOATING
#define PORTC_PIN7_VALUE  DIO_CNG_FLOATING

#define PORTD_PIN0_VALUE  DIO_CNG_FLOATING
#define PORTD_PIN1_VALUE  DIO_CNG_FLOATING
#define PORTD_PIN2_VALUE  DIO_CNG_FLOATING
#define PORTD_PIN3_VALUE  DIO_CNG_FLOATING
#define PORTD_PIN4_VALUE  DIO_CNG_FLOATING
#define PORTD_PIN5_VALUE  DIO_CNG_FLOATING
#define PORTD_PIN6_VALUE  DIO_CNG_FLOATING
#define PORTD_PIN7_VALUE  DIO_CNG_FLOATING

#endif /* MCAL_DIO_CFG_H_ */
